version: "3.4"


services:
  postgres_db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:14.13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - ./init-sql:/docker-entrypoint-initdb.d
  app: 
    container_name: api
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - postgres_db