definitions:
  models.Cart:
    properties:
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/models.CartItem'
        type: array
    type: object
  models.CartItem:
    properties:
      cart_id:
        type: integer
      id:
        type: integer
      product:
        type: string
      quantity:
        type: integer
    type: object
  models.ItemDto:
    properties:
      product:
        type: string
      quantity:
        type: integer
    type: object
  models.ResponseError:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
  title: Trainee cart-Api
  version: "1.0"
paths:
  /carts:
    get:
      description: get all carts with composition item slice inside
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Cart'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: List carts
      tags:
      - carts
    post:
      description: create cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Creates a new cart and id generated
      tags:
      - carts
  /carts/{cartId}/items:
    post:
      consumes:
      - application/json
      parameters:
      - description: cart id
        in: path
        name: cartId
        required: true
        type: integer
      - description: item to add
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.ItemDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CartItem'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Add item to cart
      tags:
      - items
  /carts/{cartId}/items/{itemId}:
    delete:
      description: delete item from cart, using cart id and item id
      parameters:
      - description: Cart id
        in: path
        name: cartId
        required: true
        type: integer
      - description: Item id
        in: path
        name: itemId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Delete an item from cart
      tags:
      - items
  /carts/{id}:
    delete:
      description: delete a cart with its items recursively
      parameters:
      - description: Cart id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Delete a cart
      tags:
      - carts
    get:
      description: get cart by id
      parameters:
      - description: id to find cart
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Shows cart by id
      tags:
      - carts
swagger: "2.0"
